AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a static website using S3 and Cloudfront for the frontend UI 

# Stack-level tags
Metadata:
  AWS::CloudFormation::Interface:
    Tags:
      - Key: Owner
        Value: !Ref OwnerName
      - Key: Description
        Value: !Ref AppDescription
      - Key: Environment
        Value: !Ref EnvPrefix
      - Key: AppName
        Value: !Ref AppName

# Parameters
Parameters:

  AppName:
    Default: cozyhomeaway-ui
    Type: String
    Description: App name
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9_-]*"
  EnvPrefix:
    Default: prod
    Type: String
    Description: Environment prefix
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9_-]*"
  BucketName:
    Default: bf-prod-s3-cozyhomeaway-ui
    Type: String
    Description: Bucket name
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9_-]*"
  HostedZoneId:
    Type: String
    Description: Hosted Zone ID for Route53 and ACM
  OwnerName:
    Default: "Brent Foster"
    Type: String
    Description: Owner name
  AppDescription:
    Default: "Cozy Home Away Static Website"
    Type: String
    Description: Tag to create.
  DomainName:
    Type: String
    Description: Primary domain name for the website (e.g. cozyhomeaway.com)
  ParamReminder:
    Default: "Stored in Secrets Manager"
    Type: String
    Description: Reminder to reference from Secrets Manager

# Resources
Resources:

  #Cert
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
       - DomainName: !Ref DomainName
         HostedZoneId: !Ref HostedZoneId
      Tags: 
        - Key: "Name"
          Value: !Sub "${EnvPrefix}-${AppName}-cert"

  WebsiteBucket:
    Properties:
      BucketName: !Ref 'BucketName'
      BucketEncryption:
              ServerSideEncryptionConfiguration:
                - ServerSideEncryptionByDefault:
                    SSEAlgorithm: AES256
      WebsiteConfiguration:
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
              BlockPublicAcls: true
              BlockPublicPolicy: true
              IgnorePublicAcls: true
              RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
            Id: OpenCors
            MaxAge: '3600'
      Tags: 
        - Key: "Name"
          Value: !Sub "${BucketName}"
    Type: AWS::S3::Bucket
  
  # IAM config for cloudfront to access S3 bucket
  CloudFrontOriginIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "origin identity"

  # Associate IAM config for cloudfront with the S3 bucket
  WebUIPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket:
        Ref: WebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser:
                Fn::GetAtt: [ CloudFrontOriginIdentity , S3CanonicalUserId ]
            Action: "s3:GetObject"
            Resource: !Sub "${WebsiteBucket.Arn}/*"

  # Cloudfront CDN
  WebsiteCloudFront:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - WebsiteBucket
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt 'WebsiteBucket.RegionalDomainName'
            Id: !Ref 'WebsiteBucket'
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginIdentity}"
            OriginCustomHeaders:
              - HeaderName: Access-Control-Allow-Origin
                HeaderValue: '*'
        Enabled: 'true'
        Comment: !Sub "${EnvPrefix} - ${AppName}"
        Aliases:
          - !Ref DomainName
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: !Ref 'WebsiteBucket'
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - HEAD
            - DELETE
            - POST
            - GET
            - OPTIONS
            - PUT
            - PATCH
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: false
          ForwardedValues:
            QueryString: 'true'
            Cookies:
              Forward: none
            Headers:
              - Access-Control-Request-Headers
              - Access-Control-Request-Method
              - Origin
        PriceClass: PriceClass_100
        Restrictions:
          GeoRestriction:
            RestrictionType: whitelist
            Locations:
            - US
            - CA
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
      Tags: 
        - Key: "Name"
          Value: !Sub "${BucketName}-cdn"

  # Route53 records for CloudFront distribution
  CloudFrontAliasRecordA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${DomainName}."
      Name: !Sub "${DomainName}."
      Type: A
      AliasTarget:
        DNSName: !GetAtt WebsiteCloudFront.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      # TTL not allowed for alias records

  CloudFrontAliasRecordAAAA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${DomainName}."
      Name: !Sub "${DomainName}."
      Type: AAAA
      AliasTarget:
        DNSName: !GetAtt WebsiteCloudFront.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      # TTL not allowed for alias records

# Outputs
Outputs:
  S3WebsiteURL:
    Value: !GetAtt 'WebsiteBucket.WebsiteURL'
  CloudFrontDomain:
    Value: !GetAtt 'WebsiteCloudFront.DomainName'
  CloudFrontDistributionId:
    Description: "CloudFront Distribution ID"
    Value: !Ref WebsiteCloudFront