name: Deploy Production CloudFormation Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
      OIDC_ROLE_NAME: ${{ vars.OIDC_ROLE_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Inject Recaptcha client key
        run: |
          sed -i "s|__RECAPTCHA_CLIENT_KEY__|${{ vars.RECAPTCHA_CLIENT_KEY }}|g" src/index.html
          sed -i "s|RECAPTCHA_CLIENT_KEY|${{ vars.RECAPTCHA_CLIENT_KEY }}|g" src/assets/js/contactform.js
      - name: Inject contact form API and key
        run: |
          sed -i "s|__CONTACTFORM_API__|${{ vars.CONTACTFORM_API }}|g" src/assets/js/contactform.js
          sed -i "s|__CONTACTFORM_KEY__|${{ vars.CONTACTFORM_KEY }}|g" src/assets/js/contactform.js
      - name: Print referenced environment variables
        run: |
          echo "AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}"
          echo "OIDC_ROLE_NAME: ${{ vars.OIDC_ROLE_NAME }}"
          echo "OwnerName: ${{ vars.OWNER_NAME }}"
          echo "AppName: ${{ vars.APP_NAME }}"
          echo "AppDescription: ${{ vars.APP_DESCRIPTION }}"
          echo "HostedZoneId: ${{ vars.HOSTED_ZONE_ID }}"
          echo "RECAPTCHA_CLIENT_KEY: ${{ vars.RECAPTCHA_CLIENT_KEY }}"
          echo "CONTACTFORM_API: ${{ vars.CONTACTFORM_API }}"
          echo "CONTACTFORM_KEY: ${{ vars.CONTACTFORM_KEY }}"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.OIDC_ROLE_NAME }}
          aws-region: us-east-1

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file config/prod-stack.yaml \
            --stack-name bf-prod-cozyhomeaway-ui \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              OwnerName="${{ vars.OWNER_NAME }}" \
              AppName="${{ vars.APP_NAME }}" \
              AppDescription="${{ vars.APP_DESCRIPTION }}" \
              HostedZoneId="${{ vars.HOSTED_ZONE_ID }}" \
            --tags \
              Owner="${{ vars.OWNER_NAME }}" \
              AppName="${{ vars.APP_NAME }}" \
              Description="${{ vars.APP_DESCRIPTION }}"

      - name: Copy src contents to S3 bucket
        run: |
          BUCKET_NAME=$(aws cloudformation describe-stacks \
            --stack-name bf-prod-cozyhomeaway-ui \
            --query "Stacks[0].Parameters[?ParameterKey=='BucketName'].ParameterValue" \
            --output text)
          aws s3 sync src/ s3://$BUCKET_NAME/ --delete
